
    create table budgets (
        amount numeric(38,2) not null,
        month varchar(7) not null,
        category_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        primary key (id)
    );

    create table categories (
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table goals (
        current_amount numeric(38,2),
        deadline date,
        target_amount numeric(38,2) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table transactions (
        amount numeric(38,2) not null,
        date date not null,
        category_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        type varchar(10) not null check (type in ('INCOME','EXPENSE')),
        description varchar(255),
        primary key (id)
    );

    create table users (
        created_at timestamp(6),
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        role varchar(255),
        primary key (id)
    );

    alter table if exists budgets 
       add constraint FKn7qib00712y8dwelmqfwis6ka 
       foreign key (category_id) 
       references categories;

    alter table if exists budgets 
       add constraint FKln0tm5tgf3f9q3sp9sa5m8m7b 
       foreign key (user_id) 
       references users;

    alter table if exists categories 
       add constraint FKghuylkwuedgl2qahxjt8g41kb 
       foreign key (user_id) 
       references users;

    alter table if exists goals 
       add constraint FKb1mp6ulyqkpcw6bc1a2mr7v1g 
       foreign key (user_id) 
       references users;

    alter table if exists transactions 
       add constraint FKsqqi7sneo04kast0o138h19mv 
       foreign key (category_id) 
       references categories;

    alter table if exists transactions 
       add constraint FKqwv7rmvc8va8rep7piikrojds 
       foreign key (user_id) 
       references users;
